propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  department:
    _attributes: { phpName: Department }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '100', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  designation:
    _attributes: { phpName: Designation }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    department_id: { type: INTEGER, size: '11', required: false, foreignTable: department, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    title: { type: VARCHAR, size: '100', required: true }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_designation_department: [department_id] }
  employee:
    _attributes: { phpName: Employee }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    department_id: { type: INTEGER, size: '11', required: false, foreignTable: department, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    designation_id: { type: INTEGER, size: '11', required: false, foreignTable: designation, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    emp_category: { type: VARCHAR, size: '10', required: false }
    name: { type: VARCHAR, size: '100', required: false }
    cnic: { type: VARCHAR, size: '50', required: false }
    dob: { type: DATE, required: false }
    gender: { type: VARCHAR, size: '10', required: false }
    mail_address: { type: VARCHAR, size: '255', required: false }
    contact_res: { type: VARCHAR, size: '50', required: false }
    contact_cell: { type: VARCHAR, size: '50', required: false }
    contact_off: { type: VARCHAR, size: '50', required: false }
    emergency_contact: { type: VARCHAR, size: '50', required: false }
    employment_date: { type: DATE, required: false }
    local_resident: { type: VARCHAR, size: '3', required: false }
    qualification: { type: VARCHAR, size: '1000', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_employee_department: [department_id], FK_employee_designation: [designation_id] }
  patient:
    _attributes: { phpName: Patient }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    id_number: { type: VARCHAR, size: '20', required: false }
    cnic: { type: VARCHAR, size: '25', required: false }
    name: { type: VARCHAR, size: '100', required: false }
    father_name: { type: VARCHAR, size: '50', required: false }
    dob: { type: DATE, required: false }
    gender: { type: VARCHAR, size: '10', required: false }
    address: { type: VARCHAR, size: '255', required: false }
    contact_res: { type: VARCHAR, size: '20', required: false }
    contact_cell: { type: VARCHAR, size: '20', required: false }
    emergency_contact: { type: VARCHAR, size: '20', required: false }
    email: { type: VARCHAR, size: '100', required: false }
    blood_group: { type: VARCHAR, size: '5', required: false }
    disease: { type: VARCHAR, size: '255', required: false }
    allergy: { type: VARCHAR, size: '255', required: false }
    drug_allergy: { type: VARCHAR, size: '255', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  pharma:
    _attributes: { phpName: Pharma }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '100', required: false }
    strength: { type: VARCHAR, size: '10', required: false }
    company: { type: VARCHAR, size: '100', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  user:
    _attributes: { phpName: User }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    role_id: { type: INTEGER, size: '11', required: false }
    username: { type: VARCHAR, size: '50', required: false }
    password: { type: VARCHAR, size: '50', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  ward:
    _attributes: { phpName: Ward }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '255', required: false }
    status: { type: VARCHAR, size: '10', required: false }
  ward_bed:
    _attributes: { phpName: WardBed }
    id: { type: INTEGER, size: '11', primaryKey: true, required: true }
    ward_id: { type: INTEGER, size: '11', required: false }
    bed: { type: VARCHAR, size: '100', required: false }
    status: { type: VARCHAR, size: '10', required: false }
