default:
  http_metas:
    content-type: text/html

  metas:
    #title:        Hospital Management System (HMIS)
    #description:  symfony project
    #keywords:     symfony, HMIS, hmis
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]
  stylesheets:    [style.css]
  stylesheets:    [iecss.css]

  javascripts:    [livevalidation_standalone.compressed.js]

  has_layout:     on
  layout:         layout
