propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  department:
    _attributes: { phpName: Department }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '100', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  designation:
    _attributes: { phpName: Designation }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    department_id: { type: INTEGER, size: '11', required: false, foreignTable: department, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    title: { type: VARCHAR, size: '100', required: true }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_designation_department: [department_id] }
  dosage:
    _attributes: { phpName: Dosage }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '50', required: false }
    status: { type: VARCHAR, size: '10', required: false }
  duty_place:
    _attributes: { phpName: DutyPlace }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '100', required: false }
    description: { type: VARCHAR, size: '255', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  duty_roster:
    _attributes: { phpName: DutyRoster }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    employee_id: { type: INTEGER, size: '11', required: false, foreignTable: employee, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    duty_place_id: { type: INTEGER, size: '11', required: false, foreignTable: duty_place, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    duty_date: { type: DATE, required: false }
    from: { type: VARCHAR, size: '10', required: false }
    to: { type: VARCHAR, size: '10', required: false }
    present: { type: VARCHAR, size: '5', required: false }
    substitute_id: { type: INTEGER, size: '11', required: false, foreignTable: employee, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_duty_roster_employee: [employee_id], FK_duty_roster_place: [duty_place_id], FK_duty_roster_substitute: [substitute_id] }
  employee:
    _attributes: { phpName: Employee }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    department_id: { type: INTEGER, size: '11', required: false, foreignTable: department, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    designation_id: { type: INTEGER, size: '11', required: false, foreignTable: designation, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    role_id: { type: INTEGER, size: '11', required: false, foreignTable: role, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    emp_category: { type: VARCHAR, size: '10', required: false }
    name: { type: VARCHAR, size: '100', required: false }
    cnic: { type: VARCHAR, size: '50', required: false }
    dob: { type: DATE, required: false }
    gender: { type: VARCHAR, size: '10', required: false }
    mail_address: { type: VARCHAR, size: '255', required: false }
    contact_res: { type: VARCHAR, size: '50', required: false }
    contact_cell: { type: VARCHAR, size: '50', required: false }
    contact_off: { type: VARCHAR, size: '50', required: false }
    emergency_contact: { type: VARCHAR, size: '50', required: false }
    employment_date: { type: DATE, required: false }
    local_resident: { type: VARCHAR, size: '3', required: false }
    qualification: { type: VARCHAR, size: '1000', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_employee_department: [department_id], FK_employee_designation: [designation_id], FK_employee_role: [role_id] }
  lab_report:
    _attributes: { phpName: LabReport }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    patient_id: { type: INTEGER, size: '11', required: false, foreignTable: patient, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    visit_id: { type: INTEGER, size: '11', required: false, foreignTable: visit, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    lab_test_id: { type: INTEGER, size: '11', required: false, foreignTable: lab_test, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    description: { type: VARCHAR, size: '1024', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_lab_report_patient: [patient_id], FK_lab_report_visit: [visit_id], FK_lab_report_lab_test: [lab_test_id] }
  lab_test:
    _attributes: { phpName: LabTest }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '255', required: false }
    description: { type: VARCHAR, size: '500', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  patient:
    _attributes: { phpName: Patient }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    id_number: { type: VARCHAR, size: '20', required: false }
    cnic: { type: VARCHAR, size: '25', required: false }
    username: { type: VARCHAR, size: '50', required: false }
    password: { type: VARCHAR, size: '50', required: false }
    name: { type: VARCHAR, size: '100', required: false }
    father_name: { type: VARCHAR, size: '50', required: false }
    dob: { type: DATE, required: false }
    gender: { type: VARCHAR, size: '10', required: false }
    address: { type: VARCHAR, size: '255', required: false }
    contact_res: { type: VARCHAR, size: '20', required: false }
    contact_cell: { type: VARCHAR, size: '20', required: false }
    emergency_contact: { type: VARCHAR, size: '20', required: false }
    email: { type: VARCHAR, size: '100', required: false }
    blood_group: { type: VARCHAR, size: '5', required: false }
    disease: { type: VARCHAR, size: '255', required: false }
    allergy: { type: VARCHAR, size: '255', required: false }
    drug_allergy: { type: VARCHAR, size: '255', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  pharma:
    _attributes: { phpName: Pharma }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '100', required: false }
    type: { type: VARCHAR, size: '50', required: false }
    strength: { type: VARCHAR, size: '10', required: false }
    company: { type: VARCHAR, size: '100', required: false }
    price: { type: INTEGER, size: '6', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  role:
    _attributes: { phpName: Role }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '50', required: false }
    status: { type: VARCHAR, size: '10', required: false }
  room:
    _attributes: { phpName: Room }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '50', required: false }
    description: { type: VARCHAR, size: '255', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
  user:
    _attributes: { phpName: User }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    role_id: { type: INTEGER, size: '11', required: false, foreignTable: role, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    employee_id: { type: INTEGER, size: '11', required: false, foreignTable: employee, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    user: { type: VARCHAR, size: '50', required: false }
    password: { type: VARCHAR, size: '50', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_user_employee: [employee_id], FK_user_role: [role_id] }
  visit:
    _attributes: { phpName: Visit }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    patient_id: { type: INTEGER, size: '11', required: false, foreignTable: patient, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    doctor_id: { type: INTEGER, size: '11', required: false, foreignTable: employee, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    ward_bed_id: { type: INTEGER, size: '11', required: false, foreignTable: ward_bed, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    ward_doc_id: { type: INTEGER, size: '11', required: false, foreignTable: employee, foreignReference: id, onDelete: RESTRICT, onUpdate: RESTRICT }
    visit_type: { type: VARCHAR, size: '10', required: false }
    medicine: { type: VARCHAR, size: '500', required: false }
    bp: { type: VARCHAR, size: '10', required: false }
    temp: { type: VARCHAR, size: '10', required: false }
    pulse: { type: VARCHAR, size: '10', required: false }
    injection: { type: VARCHAR, size: '500', required: false }
    diet: { type: VARCHAR, size: '500', required: false }
    description: { type: VARCHAR, size: '5000', required: false }
    time: { type: VARCHAR, size: '10', required: false }
    visit_date: { type: DATE, required: false }
    fee: { type: VARCHAR, size: '10', required: false }
    fee_paid: { type: VARCHAR, size: '10', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    created_at: { type: DATE, required: false }
    updated_at: { type: DATE, required: false }
    _indexes: { FK_visit_patient: [patient_id], FK_visit_doctor: [doctor_id], FK_visit_ward_bed: [ward_bed_id], FK_visit_ward_doc: [ward_doc_id] }
  ward:
    _attributes: { phpName: Ward }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    title: { type: VARCHAR, size: '255', required: false }
    status: { type: VARCHAR, size: '10', required: false }
  ward_bed:
    _attributes: { phpName: WardBed }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    ward_id: { type: INTEGER, size: '11', required: false, foreignTable: ward, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    bed: { type: VARCHAR, size: '100', required: false }
    status: { type: VARCHAR, size: '10', required: false }
    _indexes: { FK_ward_bed_ward: [ward_id] }
